Make build/archive.py Python3-compatible.
The script was mostly working, but failing at the end with:

    Traceback (most recent call last):
      File "/data/src/goma/client/./build/archive.py", line 294, in <module>
        sys.exit(main())
      File "/data/src/goma/client/./build/archive.py", line 283, in main
        m = re.search(r'(compiler-proxy[- a-zA-Z0-9:.@]*Z)', cp.read())
      File "/usr/lib64/python3.9/re.py", line 201, in search
        return _compile(pattern, flags).search(string)
    TypeError: cannot use a string pattern on a bytes-like object

Make the pattern a bytes object in Python 3 so we can match it against
the contents of cp.read(). This is also compatible with Python 2.

Change-Id: Iba1f7f355be3654ca5414b1adfeb0460934b72fb