Revert "Add service account for ci and try"
This reverts commit 4df4441ea9ae9291a1f2f9a144a10805f9c942ba.

This caused ci/try failure.

ERROR: Access denied: Auth error while calling swarming on behalf of
user:shinyak@google.com: {"error": {"message": "Service account
\"goma-client-ext-try-builders@chops-service-accounts.iam.gserviceaccount.com\"
is not allowed in the pool \"luci.flex.try\", see pools.cfg"}}